const express = require('express')
const router = express.Router()

router.post('/api/generate-commit', async (req, res) => {
    const { prompt } = req.body;

    if (!prompt) {
        console.log('Prompt is empty.');
        return;
    }

    try {
        const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${process.env.OPENROUTER_API_KEY}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                "model": "deepseek/deepseek-chat:free",
                "max_tokens": 100,
                "messages": [
                    {
                        "role": "user",
                        "content": prompt
                    }
                ]
            })
        });

        const data = await response.json();
        const modelResponse = data.choices[0].message.content;

        if (!modelResponse) {
            console.log("No response generated by the model.");
            return res.status(500).json({ message: 'No response generated by the model.' });
        } else {
            console.log(`Generated commit message: ${modelResponse}`);
            return res.status(200).json({ modelResponse: modelResponse, message: 'Successfully generated commit message.' });
        }
    } catch (error) {
        console.log('Error in generating a git commit message: ', error);
        return res.status(500).json({ message: 'Failed to generate commit message.' });
    }
})

module.exports = router